name: pyftp_gui
description: "pyftpdlib GUI version."
publish_to: 'none'
version: 1.2.7

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  process_run: ^0.14.2
  shared_preferences: ^2.2.3
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon.png"